### ISSUE TITLE
Archived of items

### ISSUE THREAD

**Issue by MO7D** [getk2/k2-v3-dev-build#221]
the new version of K2 do not have archive of items please work on it!!!!

**Comment by fevangelou** [comment]
Are you referring to listings by date?

**Comment by paulvanharen** [comment]
In Joomla! there is an archived state, next to trashed and unpublished. I would assume the request is referring to a state like this.
![k2 v3 x preview administration articles edit](https://cloud.githubusercontent.com/assets/2847593/13662119/70151590-e698-11e5-916e-21070b2a18d5.png)

**Comment by fevangelou** [comment]
Well, K2 doesn't need this. Joomla has (since forever) used "archived" articles to be able to display them in a date ordered fashion. This comes from the Mambo days to be exact and it was a hackish way to display articles grouped by month.

This is not needed in K2 of course as it has menu items to display K2 content grouped by date.

Please confirm this is what you're referring to.
