### ISSUE TITLE
Provide Multiple Categories (Core K2)

### ISSUE THREAD

**Issue by heyjoecampbell** [getk2/k2-v3-dev-build#290]
Multiple categories is a standard and widely accepted/used feature of WordPress.

I am confused as to why a CMS would limit where you can place content. Think about it, by NOT allowing multiple categories, is like saying "create amazing content, but you can only have it live in one category."

This may have been ok or even ideal back in the web 1.0 days, but now when an organization wants to dominate an industry and a piece of content can have multiple application - there is a valid need for such content to be placed in multiple categories.

Let's take a look at two SEO leaders (Moz and Yoast), go to each main blog page and you will find that most posts live in multiple categories:

https://moz.com/blog
https://yoast.com/seo-blog/

My thought, if it's good enough for Moz and Yoast, then it's good enough for me :)

If offering a multi-category feature will comprise performance, then I would recommend offering it as a parameter that can be activated (deactivated by default) This way a user can utilize it at their discretion. The main point, is that this feature should a core K2 feature - developed, optimized and maintained by those who know K2 best :)

This is not a rant, but constructive criticism, as we all need to challenge the K2 Community from the JW developers, to third-party K2 extension developers, to site admins. There's an old saying "iron sharpens iron." So let's challenge each other respectfully in the spirit of PROGRESS :)

**Comment by Bonitto** [comment]
Although I am not user of K2 yet (I primarily use EasyBlog), I most certainly would have to agree with you. I think multiple and/or nested categories is quite common in other CMS's and a necessity in today's heavily content driven market. For my client, Radiology Affiliates Imaging, we write content that overlaps several categories in their target market (Women's Heath and procedures such as an MRI, CT-Scan, Ultrasound). 

Furthermore, I believe we've seen industry leaders move towards this functionality because it provides an improved user-experience and it allows the user to view content based on their specific interests and quite frankly sometimes those interests overlap.

**Comment by mabdelaziz77** [comment]
I totally agree with your request, multiple categories is a great enhancement which is, I can say, heavily needed.

Really I can't imagine a catalog or listings website, for example, without this feature, although in some cases tags can be used if it is only a classification issue.

I don't think it will degrade the performance to a great extent, the performance is a matter of design and implementation.

**Comment by heyjoecampbell** [comment]
I another good indicator is the use of third-party plugins that provide the functionality. 

There is a need/demand for the multiple categories. 

To your point about tags @mabdelaziz77 - I wrote this post about K2 Categories vs. Tags:
http://www.joomlaworks.net/forum/k2-en/44148-k2-tags-vs-categories

**Comment by fevangelou** [comment]
Multiple categories can't work out of the box in Joomla due to how Joomla constructs URLs (it's a router issue to be exact).

There are "hack-ish" solutions for that which can be used today, e.g.: http://extensions.joomla.org/extension/additional-categories-for-k2

In other words, K2 not having multiple categories already is a limitation posed by Joomla.
