### ISSUE TITLE
Feature request: Meta Title

### ISSUE THREAD

**Issue by heyjoecampbell** [getk2/k2-v3-dev-build#79]
Offer a parameter for meta title on item page, instead of only pulling it from item title.

**Comment by paulvanharen** [comment]
Hi Joe,

Can you say a few words on the benefits of this? It seems not too complicated to implement this, but it clutters up the item interface with yet one more parameter to control. Thus, I would like to understand the benefit.

Thanks, Paul

**Comment by kricore** [comment]
I agree with Paul on this one. 
The benefit would be to have control over your site's meta tags, eg strip it down to exactly 70 characters or Google's limit. 

This is not intended for the majority of users (like the tags) there is no need to put it in the main form. Since the options for inserting custom metadata (keywords, description) are already present under the "Metadata & Publishing" tab, I propose (if we are implementing) to be placed in that set of similar fields.

**Comment by heyjoecampbell** [comment]
Hi Paul & Krikor,

We are in the web optimization age, which calls for granular control of page details. A page's meta data included in such details. There are benefits to controlling a site/page's: Meta Title, Meta Description, and even Image File Name (that is for another post).

This is especially needed for items that do not have a direct menu item (which is common for blog and directory items).

Anyone who is interested in SEO is required to use a third-party extension (or) use use an override with extra fields posted to the head by way of the addCustomTag. This is the method I use, which requires a bit of coding.

All I am suggesting is that K2 be better positioned for Search Engine Optimization. Extracting meta data from an item title and intro/fulltext is below the current standard. 

Regards,

Joe

**Comment by fevangelou** [comment]
You're definitely on a roll :)

What you're suggesting would be great for an SEO plugin for K2. So here's a dev idea ;)

By leveraging K2's API, it's very easy to add any number of custom fields in the K2 item page's content tabs. So in this case, it would be a matter of adding an "SEO" section just below the item's introtext/fulltext fields.

I'm changing the label to plugin.

**Comment by heyjoecampbell** [comment]
This leads to two other thoughts that I had:

* How does an idea by a non-developer make it's way to a developer for the development of an extension? I think this process needs to be nurtured. 

* K2 plugins should be housed in tabs vs. being placed under standard item elements - this is why I suggested the control of default K2 tabs (so a user could remove **Media** and **Attachments** tabs and add **SEO** and **J2Store** tabs)

**Comment by fevangelou** [comment]
K2 Plugins can indeed have their own tab. They don't need to be under any existing tab. It has been like this since the inception of the K2 API.

Now for the rest of your comments, I guess GitHub is the right place for now. That's why I added the new "k2 plugin" label, so it's easy to sort stuff we could put into one or more plugins.

I think there is definitely room for such an extension.

**Comment by heyjoecampbell** [comment]
Awesome +1

**Comment by paulvanharen** [comment]
I'll implement the title meta tag similar to the other meta tags.
At some later point we may decide to move the rendering to a plug-in for better control.

**Comment by fevangelou** [comment]
Since the data for meta tags is now stored in a single column, we now have the freedom to add more in the future, perhaps even those related to Open Graph as well, for more granular control.

**Comment by heyjoecampbell** [comment]
I would love to see Open Graphic andTwitter Card integration. Even a Custom Code option would be nice.
